networks:
  pollbook:
    ipam:
      config:
      - gateway: 172.16.0.1
        subnet: 172.16.0.0/16
services:
  checkin:
    build: .
    container_name: checkin
    cpuset: '0'
    develop:
      watch:
      - action: sync
        path: .
        target: /epollbook
    environment:
      PYTHONUNBUFFERED: '1'
      SERVICE_ROLE: checkin
      TZ: America/New_York
    image: epollbook:latest
    mem_limit: 8g
    networks:
      pollbook:
        ipv4_address: 172.16.0.5
    stdin_open: true
    tty: true
    working_dir: /epollbook/build/apps/docker-test-deployment/checkin_server
  dummy-id:
    container_name: dummy-id
    cpuset: '0'
    develop:
      watch:
      - action: sync
        path: .
        target: /epollbook
    environment:
      PYTHONUNBUFFERED: '1'
      SERVICE_ROLE: id
      TZ: America/New_York
    image: epollbook:latest
    mem_limit: 8g
    networks:
      pollbook:
        ipv4_address: 172.16.0.6
    stdin_open: true
    tty: true
    working_dir: /epollbook/build/apps/docker-test-deployment/id_server
  trusted-client-1:
    container_name: trusted-client-1
    develop:
      watch:
      - action: sync
        path: .
        target: /epollbook
    environment:
      CLIENT_ID: '1'
      PYTHONUNBUFFERED: '1'
      TRUSTED: '1'
      TZ: America/New_York
    image: epollbook:latest
    mem_limit: 8g
    networks:
      pollbook:
        ipv4_address: 172.16.0.101
    stdin_open: true
    tty: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client1
  untrusted-client-0:
    container_name: untrusted-client-0
    develop:
      watch:
      - action: sync
        path: .
        target: /epollbook
    environment:
      CLIENT_ID: '0'
      PYTHONUNBUFFERED: '1'
      TRUSTED: '0'
      TZ: America/New_York
    image: epollbook:latest
    mem_limit: 8g
    networks:
      pollbook:
        ipv4_address: 172.16.0.100
    stdin_open: true
    tty: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client0
