services:
  checkin:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/checkin_server
    develop:
      watch:
        - path: .
          target: /epollbook
          action: sync
    networks:
      pollbook:
        ipv4_address: 172.16.0.5
  dummy-id:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/id_server
    develop:
      watch:
        - path: .
          target: /epollbook
          action: sync
    networks:
      pollbook:
        ipv4_address: 172.16.0.6
  untrusted-client-0:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client0
    networks: [pollbook]
    environment:
      TRUSTED_NAME: trusted-client-1

  trusted-client-1:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client1
    develop:
      watch:
        - path: .
          target: /epollbook
          action: sync
    networks: [pollbook]
    environment:
      TRUSTED_NAME: trusted-client-1

  untrusted-client-2:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client2
    networks: [pollbook]
    develop:
      watch:
        - path: .
          target: /epollbook
          action: sync
    environment:
      TRUSTED_NAME: trusted-client-3

  trusted-client-3:
    build: .
    tty: true
    stdin_open: true
    working_dir: /epollbook/build/apps/docker-test-deployment/client3
    develop:
      watch:
        - path: .
          target: /epollbook
          action: sync
    networks: [pollbook]

networks:
  pollbook:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
