#!/bin/bash
# This script deletes all the files generated by generate_keys.sh

rm -r ca
rm -r checkin_server/ca
rm -r id_server/ca

rm checkin_server/*.pem
rm id_server/*.pem

for num in {0..3}; do
    rm -r client${num}/ca
    rm client${num}/*.pem
done
